/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library lui
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include "lui/Application.h"
#include "lui/Window.h"

using namespace lui;

extern "C" {
int luaopen_lui_Application(lua_State *L);
int luaopen_lui_Window(lua_State *L);
}

// --=============================================== FUNCTIONS
static const struct luaL_Reg lui_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_lui_core(lua_State *L) {
  lua_newtable(L);
  // <lib>
  dub::fregister(L, lui_functions);
  // <lib>

  luaopen_lui_Application(L);
  // <lui.Application>
  lua_setfield(L, -2, "Application");
  
  luaopen_lui_Window(L);
  // <lui.Window>
  lua_setfield(L, -2, "Window");
  
  // <lib>
  return 1;
}
