/**
 *
 * MACHINE GENERATED FILE. DO NOT EDIT.
 *
 * Bindings for library lui
 *
 * This file has been generated by dub 2.2.0.
 */
#include "dub/dub.h"
#include "lui/Application.h"
#include "lui/FileHandle.h"
#include "lui/Timer.h"
#include "lui/View.h"

using namespace lui;

extern "C" {
int luaopen_lui_Application(lua_State *L);
int luaopen_lui_FileHandle(lua_State *L);
int luaopen_lui_Timer(lua_State *L);
int luaopen_lui_View(lua_State *L);
}

// --=============================================== FUNCTIONS
static const struct luaL_Reg lui_functions[] = {
  { NULL, NULL},
};


extern "C" int luaopen_lui_core(lua_State *L) {
  lua_newtable(L);
  // <lib>
  dub::fregister(L, lui_functions);
  // <lib>

  luaopen_lui_Application(L);
  // <lui.Application>
  lua_setfield(L, -2, "Application");
  
  luaopen_lui_FileHandle(L);
  // <lui.FileHandle>
  lua_setfield(L, -2, "FileHandle");
  
  luaopen_lui_Timer(L);
  // <lui.Timer>
  lua_setfield(L, -2, "Timer");
  
  luaopen_lui_View(L);
  // <lui.View>
  lua_setfield(L, -2, "View");
  
  // <lib>
  return 1;
}
